services: 
  db: 
    image: mariadb:latest 
    command: '--default-authentication-plugin=mysql_native_password' 
    volumes: 
      - db_data:/var/lib/mysql 
    restart: always 
    environment: 
      - MYSQL_ROOT_PASSWORD=reas2024 
      - MYSQL_DATABASE=wordpress 
      - MYSQL_USER=wordpress 
      - MYSQL_PASSWORD=wordpress 
    expose: 
      - 3306 
      - 33060 
  wordpress1: 
    image: wordpress:latest 
    volumes: 
      - wp_data:/var/www/html 
    ports: 
      - 81:80 
    restart: always 
    environment: 
      - WORDPRESS_DB_HOST=db 
      - WORDPRESS_DB_USER=wordpress 
      - WORDPRESS_DB_PASSWORD=wordpress 
      - WORDPRESS_DB_NAME=wordpress 

  wordpress2: 
    image: wordpress:latest 
    volumes: 
      - wp_data:/var/www/html 
    ports: 
      - 82:80 
    restart: always 
    environment: 
      - WORDPRESS_DB_HOST=db 
      - WORDPRESS_DB_USER=wordpress 
      - WORDPRESS_DB_PASSWORD=wordpress 
      - WORDPRESS_DB_NAME=wordpress

  wordpress3: 
    image: wordpress:latest 
    volumes: 
      - wp_data:/var/www/html 
    ports: 
      - 83:80 
    restart: always 
    environment: 
      - WORDPRESS_DB_HOST=db 
      - WORDPRESS_DB_USER=wordpress 
      - WORDPRESS_DB_PASSWORD=wordpress 
      - WORDPRESS_DB_NAME=wordpress
  nginx:
    image: nginx:latest
    ports:
      - "80:80"  
    depends_on:
      - wordpress1
      - wordpress2
      - wordpress3
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
volumes: 
  db_data: 
  wp_data: 